//FOR SEND OTP
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAILURE = 'SEND_OTP_FAILURE';

//FOR VERIFY OTP
export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

export const SET_LOGGEDIN = 'SET_LOGGEDIN';

//FOR LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//FOR GET USER SUMMARY DETAILS
export const GET_USER_SUMMARY_REQUEST = 'GET_USER_SUMMARY_REQUEST';
export const GET_USER_SUMMARY_SUCCESS = 'GET_USER_SUMMARY_SUCCESS';
export const GET_USER_SUMMARY_FAILURE = 'GET_USER_SUMMARY_FAILURE';

//FOR GET USER PROFILE DETAILS
export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

//FOR GET RETAILERS DETAILS
export const GET_RETAILERS_REQUEST = 'GET_RETAILERS_REQUEST';
export const GET_RETAILERS_SUCCESS = 'GET_RETAILERS_SUCCESS';
export const GET_RETAILERS_FAILURE = 'GET_RETAILERS_FAILURE';

export const SET_RETAILERS_SHOP_INFO_REQUEST =
  'SET_RETAILERS_SHOP_INFO_REQUEST';
export const SET_RETAILERS_SHOP_INFO = 'SET_RETAILERS_SHOP_INFO';

//FOR GET RETAILER SHOP INFO
export const GET_RETAILER_SHOPINFO_REQUEST = 'GET_RETAILER_SHOPINFO_REQUEST';
export const GET_RETAILER_SHOPINFO_SUCCESS = 'GET_RETAILER_SHOPINFO_SUCCESS';
export const GET_RETAILER_SHOPINFO_FAILURE = 'GET_RETAILER_SHOPINFO_FAILURE';

//FOR GET THE LANDMARK
export const GET_LANDMARK_REQUEST = 'GET_LANDMARK_REQUEST';
export const GET_LANDMARK_SUCCESS = 'GET_LANDMARK_SUCCESS';
export const GET_LANDMARK_FAILURE = 'GET_LANDMARK_FAILURE';

//FOR GET THE BRAND FOR LOYALITY PROGRAM
export const GET_BRAND_REQUEST = 'GET_BRAND_REQUEST';
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS';
export const GET_BRAND_FAILURE = 'GET_BRAND_FAILURE';


export const UPDATE_RETAILERS_SHOPINFO_REQUEST = "UPDATE_RETAILERS_SHOPINFO_REQUEST"
export const UPDATE_RETAILERS_SHOPINFO_SUCCESS = "UPDATE_RETAILERS_SHOPINFO_SUCCESS"
export const UPDATE_RETAILERS_SHOPINFO_FAILURE = "UPDATE_RETAILERS_SHOPINFO_FAILURE"

// FOR SKU
export const GET_PRODUCT_CATEGORIES_REQUEST = "GET_PRODUCT_CATEGORIES_REQUEST"
export const GET_PRODUCT_CATEGORIES_SUCCESS = "GET_PRODUCT_CATEGORIES_SUCCESS"
export const GET_PRODUCT_CATEGORIES_FAILURE = "GET_PRODUCT_CATEGORIES_FAILURE"

// FOR UPDATE RETAILER STORE IMAGES
export const UPDATE_RETAILER_STOREIMAGES_REQUEST = "UPDATE_RETAILER_STOREIMAGES_REQUEST"
export const UPDATE_RETAILER_STOREIMAGES_SUCCESS = "UPDATE_RETAILER_STOREIMAGES_SUCCESS"
export const UPDATE_RETAILER_STOREIMAGES_FAILURE = "UPDATE_RETAILER_STOREIMAGES_FAILURE"